/* tslint:disable */
/* eslint-disable */
/**
 * MW Bank ENSIT
 * MaibornWolff Bank - ENSIT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/account-rest-service-api';
export * from './api/transfer-rest-service-api';

