/* tslint:disable */
/* eslint-disable */
/**
 * MW Bank ENSIT
 * MaibornWolff Bank - ENSIT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountDto
 */
export interface AccountDto {
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    lastName?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountDto
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    updatedAt?: string;
}


