/* tslint:disable */
/* eslint-disable */
/**
 * MW Bank ENSIT
 * MaibornWolff Bank - ENSIT
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountDto } from './account-dto';

/**
 * 
 * @export
 * @interface TransferDto
 */
export interface TransferDto {
    /**
     * 
     * @type {string}
     * @memberof TransferDto
     */
    id?: string;
    /**
     * 
     * @type {AccountDto}
     * @memberof TransferDto
     */
    from?: AccountDto;
    /**
     * 
     * @type {AccountDto}
     * @memberof TransferDto
     */
    to?: AccountDto;
    /**
     * 
     * @type {number}
     * @memberof TransferDto
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof TransferDto
     */
    createdAt?: string;
}


